apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: ghcr.io/purisev
      chart: universal-helm-chart
      targetRevision: 3.0.0
      helm:
        releaseName: monitoring
        valueFiles:
          - $values/docs/02-examples/06-monitoring/values.yaml
    - repoURL: https://github.com/purisev/universal-helm-chart.git
      targetRevision: v3.0.0
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
