{{- if and .Values.serviceAccount.create .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "uhc.fullname" . }}
  labels:
    {{- include "uhc.labels" . | nindent 4 }}
  {{- $annots := include "uhc.metadataAnnotations" (dict "ctx" . "kind" "rbac") }}
  {{- if $annots }}
  {{- $annots | nindent 2 }}
  {{- end }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "uhc.fullname" . }}
  labels:
    {{- include "uhc.labels" . | nindent 4 }}
  {{- $annots = include "uhc.metadataAnnotations" (dict "ctx" . "kind" "rbac") }}
  {{- if $annots }}
  {{- $annots | nindent 2 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "uhc.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "uhc.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
