{{- $ctx := . }}
{{- $releaseName := include "uhc.fullname" . -}}
{{- $deploymentSpecs := $ctx.Values.deployments -}}
{{- range $wlName := keys $deploymentSpecs | sortAlpha }}
{{- $wl := index $deploymentSpecs $wlName -}}
{{- if and (hasKey $wl "enabled") $wl.enabled $wl.keda $wl.keda.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $releaseName }}-{{ $wlName }}
  labels:
    {{- include "uhc.workloadLabels" (dict "ctx" $ctx "workloadName" $wlName) | nindent 4 }}
  {{- $annots := include "uhc.metadataAnnotations" (dict "ctx" $ctx "kind" "scaledObject") }}
  {{- if $annots }}
  {{- $annots | nindent 2 }}
  {{- end }}
spec:
  scaleTargetRef:
    name: {{ $releaseName }}-{{ $wlName }}
    kind: Deployment
    envSourceContainerName: {{ $wlName }}
  minReplicaCount: {{ $wl.keda.minReplicas | default 1 }}
  maxReplicaCount: {{ required (printf "deployments.%s.keda.maxReplicas is required" $wlName) $wl.keda.maxReplicas }}
  triggers:
    {{- toYaml $wl.keda.triggers | nindent 4 }}
  {{- if $wl.keda.pollingInterval }}
  pollingInterval: {{ $wl.keda.pollingInterval }}
  {{- end }}
  {{- if $wl.keda.cooldownPeriod }}
  cooldownPeriod: {{ $wl.keda.cooldownPeriod }}
  {{- end }}
  {{- if $wl.keda.idleReplicaCount }}
  idleReplicaCount: {{ $wl.keda.idleReplicaCount }}
  {{- end }}
{{- end }}
{{- end }}
{{- $statefulSetSpecs := $ctx.Values.statefulSets | default dict -}}
{{- range $wlName := keys $statefulSetSpecs | sortAlpha }}
{{- $wl := index $statefulSetSpecs $wlName -}}
{{- if and (hasKey $wl "enabled") $wl.enabled $wl.keda $wl.keda.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $releaseName }}-{{ $wlName }}
  labels:
    {{- include "uhc.workloadLabels" (dict "ctx" $ctx "workloadName" $wlName) | nindent 4 }}
  {{- $annots := include "uhc.metadataAnnotations" (dict "ctx" $ctx "kind" "scaledObject") }}
  {{- if $annots }}
  {{- $annots | nindent 2 }}
  {{- end }}
spec:
  scaleTargetRef:
    name: {{ $releaseName }}-{{ $wlName }}
    kind: StatefulSet
    envSourceContainerName: {{ $wlName }}
  minReplicaCount: {{ $wl.keda.minReplicas | default 1 }}
  maxReplicaCount: {{ required (printf "statefulSets.%s.keda.maxReplicas is required" $wlName) $wl.keda.maxReplicas }}
  triggers:
    {{- toYaml $wl.keda.triggers | nindent 4 }}
  {{- if $wl.keda.pollingInterval }}
  pollingInterval: {{ $wl.keda.pollingInterval }}
  {{- end }}
  {{- if $wl.keda.cooldownPeriod }}
  cooldownPeriod: {{ $wl.keda.cooldownPeriod }}
  {{- end }}
  {{- if $wl.keda.idleReplicaCount }}
  idleReplicaCount: {{ $wl.keda.idleReplicaCount }}
  {{- end }}
{{- end }}
{{- end }}
