{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "uhc.serviceAccountName" . }}
  labels:
    {{- include "uhc.labels" . | nindent 4 }}
  {{- $annots := include "uhc.metadataAnnotations" (dict "ctx" . "kind" "serviceAccount" "extra" (.Values.serviceAccount.annotations | default dict)) }}
  {{- if $annots }}
  {{- $annots | nindent 2 }}
  {{- end }}
{{- end }}
