{{- $ctx := . }}
{{- $releaseName := include "uhc.fullname" . -}}
{{- $deploymentSpecs := $ctx.Values.deployments -}}
{{- range $wlName := keys $deploymentSpecs | sortAlpha }}
{{- $wl := index $deploymentSpecs $wlName }}
{{- if and (hasKey $wl "enabled") $wl.enabled }}
{{- $vpaSpec := default $ctx.Values.verticalPodAutoscaler $wl.verticalPodAutoscaler }}
{{- if and $vpaSpec (default false $vpaSpec.enabled) }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ $releaseName }}-{{ $wlName }}
  annotations:
    "argocd.argoproj.io/sync-wave": "{{ add 1 $ctx.Values.syncWaves.deploymentSyncWave | int }}"
  labels:
    {{- include "uhc.workloadLabels" (dict "ctx" $ctx "workloadName" $wlName) | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $releaseName }}-{{ $wlName }}
  updatePolicy:
    updateMode: {{ $vpaSpec.updateMode | default "Initial" }}
  {{- if $vpaSpec.resourcePolicy }}
  resourcePolicy:
    {{- toYaml $vpaSpec.resourcePolicy | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- $statefulSetSpecs := $ctx.Values.statefulSets | default dict -}}
{{- range $wlName := keys $statefulSetSpecs | sortAlpha }}
{{- $wl := index $statefulSetSpecs $wlName }}
{{- if and (hasKey $wl "enabled") $wl.enabled }}
{{- $vpaSpec := default $ctx.Values.verticalPodAutoscaler $wl.verticalPodAutoscaler }}
{{- if and $vpaSpec (default false $vpaSpec.enabled) }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ $releaseName }}-{{ $wlName }}
  annotations:
    "argocd.argoproj.io/sync-wave": "{{ add 1 $ctx.Values.syncWaves.deploymentSyncWave | int }}"
  labels:
    {{- include "uhc.workloadLabels" (dict "ctx" $ctx "workloadName" $wlName) | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ $releaseName }}-{{ $wlName }}
  updatePolicy:
    updateMode: {{ $vpaSpec.updateMode | default "Initial" }}
  {{- if $vpaSpec.resourcePolicy }}
  resourcePolicy:
    {{- toYaml $vpaSpec.resourcePolicy | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
